- name: sample play
  hosts: localhost
  tasks:
    - name: display text
      ansible.builtin.debug:
        msg: "hello iliyas"

- name: sample play
  hosts: all
  tasks:
    - name: display text
      ansible.builtin.debug:
        msg: "hello iliyas"

- name: Register a variable
  hosts: localhost
  tasks:
    - name: Get uptime output
      ansible.builtin.shell: uptime
      register: out