- name: sample play
  hosts: localhost
  tasks:
    - name: display text
      ansible.builtin.debug:
        msg: "hello iliyas"

- name: sample play
  hosts: all
  tasks:
    - name: display text
      ansible.builtin.debug:
        msg: "hello iliyas"