- name: vars
  hosts: localhost
  vars:
    url: "example.com"
  tasks:
    - name: play
      ansible.builtin.debug:
        msg: url = {{ url }}

- name: vars from file
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: play 1
      ansible.builtin.debug:
        msg: url = {{ url }}