- name: vars
  hosts: localhost
  vars:
    url: "example.com"
  tasks:
    - name: play 1
      ansible.builtin.debug:
        msg: url = {{ url }}

- name: vars from file
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: play 2
      ansible.builtin.debug:
        msg: url = {{ url }}

- name: task level vars
  hosts: localhost
  tasks:
    - name: play 3
      vars:
        url = "dev.com"
      ansible.builtin.debug:
        msg: url = {{ url }}