- name: vars
  hosts: localhost
  vars:
    url: "example.com"
  tasks:
    - name: play 1
      ansible.builtin.debug:
        msg: url = {{ url }}

- name: vars from file
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: play 2
      ansible.builtin.debug:
        msg: url = {{ url }}

- name: vars from tasks
  hosts: localhost
  tasks:
    - name: play 3
      vars:
        url: "example.tasks.com"
      ansible.builtin.debug:
        msg: url = {{ url }}

- name: vars from inventory
  hosts: all
  tasks:
    - name: play 4
      ansible.builtin.debug:
        msg: url = {{ url }}

- name: vars from cli
  hosts: localhost
  tasks:
    - name: play 5
      ansible.builtin.debug:
        msg: url = {{ urll }}

- name: Register a variable
  hosts: localhost
  tasks:
    - name: Get uptime output
      ansible.builtin.shell: uptime
      register: out

    - name: Print out
      ansible.builtin.debug:
        msg: "{{ out }}"

    - name: Declare a variable
      ansible.builtin.set_fact:
        status: "{{ out.rc }}"

    - name: Print Status
      ansible.builtin.debug:
        msg: "{{ status }}"