- name: rt var
  hosts: localhost
  tasks:
    - name: play 1
      ansible.builtin.shell: uptime
      register: var1

    - name: play 2
      ansible.builtin.debug:
        msg: "{{ var1 }}"

    - name: play 3
      ansible.builtin.set_fact:
        var2: "{{ var1.rc }}"

    - name: play 4
      ansible.builtin.debug:
        msg: "{{ var2 }}"