- name: rt var
  hosts: localhost
  tasks:
    - name: play 1
      ansible.builtin.shell: uptime
      register: show

    - name: play 2
      ansible.builtin.debug:
        msg: "{{ show }}"

    - name: play 3
      ansible.builtin.set_fact:
        status: "{{ show.rc }}"

    - name: play 4
      ansible.builtin.debug:
        msg: "{{ status }}"