- name: rt var
  hosts: localhost
  tasks:
    - name: play 1
      ansible.builtin.shell: runtime
      register: out

    - name: play 2
      ansible.builtin.debug:
        msg: "{{ out }}"

    - name: play 3
      ansible.builtin.set_fact:
        status: "{{ out.rc }}"

    - name: play 4
      ansible.builtin.debug:
        msg: "{{ status }}"