- name: create parameter
  hosts: localhost
  tasks:
    - name: para
      ansible.builtin.debug:
        msg: "{{ lookup('amazon.aws.aws_ssm', 'test'), region='us-east-1' }}"

- name: sample play
  hosts: localhost
  tasks:
    - name: display text
      ansible.builtin.debug:
        msg: "{{ lookup('amazon.aws.aws_test', 'test') }}"