- name: filter
  hosts: localhost
  vars:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
  tasks:
    - debug:
        msg: "{{ url | split('/') | last | regexp_replace ('.tar.gz', '') }}"