- hosts: localhost
  tasks:
    - debug:
        msg: kaya peru {{item}}
      loop:
        - banana
        - apply

- hosts: localhost
  tasks:
    - debug:
        msg: kaya peru {{item.name}}, enni unnai {{item.quantity}}
      loop:
        - {name:"apple", quantity:10}
        - {name:"banana", quantity:5}