#- name: role
#  ansible.builtin.debug:
#    msg: "{{ url }}"

- name: install nginx
  yum:
    name: nginx
    state: installed

- name: copy template
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf